### ISSUE TITLE
Not abel to make db Connection

### ISSUE THREAD

**Issue by parveen-oodles** [isotopo/node-odoo#11]
Hi,
I am first time using your module and as i tried according to given readme for installing and using this module.
I just simply install the npm module.
Than just copy paste  DB connection code in my file. As i run the same getting error i.e:-

> events.js:141
      throw er; // Unhandled 'error' event
       ^
 (STDERR) 
 (STDERR) Error: connect ECONNREFUSED 127.0.0.1:4569
 (STDERR)     at Object.exports._errnoException (util.js:907:11)
 (STDERR)     at exports._exceptionWithHostPort (util.js:930:20)
 (STDERR)     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)

Please help me for the same and let me know if something need to be installed prior to this module.

Thanks

**Comment by Quantium** [comment]
You need to test with a local copy of odoo or, another option is to change the url where your odoo database is available
