### ISSUE TITLE
Vulnerability in jayson's loadash

### ISSUE THREAD

**Issue by ankurloriya** [isotopo/node-odoo#12]
Low:Prototype Pollution
Package:lodash
Patched in:>=4.17.5
Dependency of:**node-odoo**
Path:**node-odoo > jayson > lodash**
More infohttps://nodesecurity.io/advisories/577

**Comment by Quantium** [comment]
Dependencies fixed for version 1.1 in e2fd6766d51c3c7b914b27451c4b448f368c9825
