### ISSUE TITLE
Search example

### ISSUE THREAD

**Issue by MattFellows** [isotopo/node-odoo#13]
Is there an example anywhere of how to provide the arguments to `odoo.search()`...
I've figured out that it needs to be an array as the outermost element, but can't work out the format to provide for search filtering :(

**Comment by AyoubElk** [comment]
This should work: 

``` javascript
 odoo.search('model', [['id', '>', '1'],['parameter', '=', false]], function (err, result) {
    if (err) { return console.log(err); }
    console.log('Result = ', JSON.stringify(result, null, 4));
  });
```

**Comment by AyoubElk** [comment]
I'll go ahead and close this issue.
Happy new year.
