### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by Quantium** [isotopo/node-odoo#14]
I'm looking for someone to maintain this code because I don't have enough time to do it right now.

The maintainers will be added to the collaborators page in npm and here in Github and the honor and glory will be with them.

**Comment by AyoubElk** [comment]
Hi Andrés, I'd be happy to help.

**Comment by Quantium** [comment]
Thank you very mucho @AyoubElk!

This package is very helpful to a lot of people. I'll help as soon as I have enough time to help.
