### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by DomSavd** [isotopo/node-odoo#5]
This project is very promosing.

But i think It should be interesting to have some documentation about how to use node-odoo on the wiki.

We should see the steps to install odoo and node-odoo on the server after that we should have a small web app development tutorials that is using node-odoo to connect and retrieve some information from odoo.

I hope someone will take the time to do this and im volunteer to help this person document and test the documentation.

Best Regards.

**Comment by Quantium** [comment]
You'r right @DomSavd . We'll be working on that on the next Sprint. Thanks for the advice.
